### ISSUE TITLE
Doesn't submit new skype status if artist or title contains "&"

### ISSUE THREAD

**Issue by ghost** [iiPing/Rhythmbox-Skype-Mood-Notifier#2]
When the artist name or the title of the song contains the character "&" the plugin doesn't change the Skype status.
(Using version 0.40, Rhythmbox 0.13.1)

**Comment by iiPing** [comment]
Koze, thanks for submitting an issue,

Quick fix has been submitted 

tested with 
simplified chinese, japanese, korean characters and the ampersand.
