### ISSUE TITLE
can't use on ubuntu 12.04 (gnome3)

### ISSUE THREAD

**Issue by kolobock** [iiPing/Rhythmbox-Skype-Mood-Notifier#3]
The module is not observed in the Modules list. on ubuntu 12.04, gnome3, python 2.7.3, skype 4, rhythmbox 2.96

I've tried to put plugin into /usr/lib/rhythmbox/plugins -- it appeared in the modules list but there was an error loading plugin.

**Comment by iiPing** [comment]
I'm checking this over the weekend, thnx

**Comment by ghost** [comment]
Same issue with me too cannot replicate this on Ubuntu 12.04 x86_64, with Skype 4.0.0.8 and Rhythbox 2.96.
And would be very happy if i can ccontribute anything.

**Comment by evileyes** [comment]
Plugin not even showing up in my rhythmbox 2.96 plugin list on UBuntu 12.04. Can anyone help how to debug or make it work?

**Comment by kevinhq** [comment]
same here, plugins not showing in plugin list on Ubuntu 12.04
- Skype 4, rhythmbox 2.96

**Comment by kolobock** [comment]
it's not interesting anymore
